name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # Tell GitHub Actions to run commands inside the subfolder
    defaults:
      run:
        working-directory: playwright-demo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test